### ISSUE TITLE
How to estimate the consumption of capacity units of a given pod and related replicas?

### ISSUE THREAD

**Issue by MissileRBM** [SAP-samples/teched2021-DEV261#1]
Dears,

my question is reported in this incident: [INC1219992](https://itsm.services.sap/now/workspace/agent/record/incident/032e8ae4dbbf3418648263cad396191d)

Thanks A Lot,

All the Best

Matteo Bollo

**Comment by mado0803** [comment]
Dear Matteo,

It's not possible to estimate the amount of Capacity Units consumed by a Docker container as other factors like invocation play a role in how much CPU and memory it consumes. If you have Kyma runtime up and running and you want to look into resource consumption by pod, there is the Dashboard "Kubernetes / Nodes". Furthermore, there is the dashboard "Kubernetes / Compute Resources / Namespace (Pods)".

Furthermore, you can define the minimum and maximum resources you assign to a deployment or a function. 

Translating this into Capacity Units could be done by looking at the amount of Capacity Units per additional Virtual Machine: The smallest VM with 8vCPU & 32 GB memory is consuming 692 CUs. Now you can convert that into the consumption of your particular deployment.

But be aware that autoscaling happens in "VM"-size steps.

Best regards,
Marco
